# Generated by Django 5.2.5 on 2026-03-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mos', '0002_create_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
